import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <script defer src= "/swup/dist/swup.min.js"></script> */}
        <script defer src="https://unpkg.com/swup@4"></script>
        <script defer src="/swupConfig.js"></script>
        <link href="transition.css" rel="stylesheet"></link>
        <script defer src="circleAnimation.js"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        {/* <div className="layout-struct"> */}
          <canvas id="background-animation">
            {/* <div className="layout-struct">
              <Navbar />
              <main id="swup" className="transition-fade">
              {children}
              <Footer />
              </main>
            </div> */}
          </canvas>
        {/* </div> */}
        <div className="layout-struct">
          <Navbar />
            <main id="swup" className="transition-fade">
              {children}
              <Footer />
            </main>
        </div>
      </body>
    </html>
  );
}
